// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// do_calculations
std::vector<std::vector<std::string> > do_calculations(double measured_mass, std::vector<int> max, std::vector<int> min, double tolerance, double charge, bool applygr);
RcppExport SEXP mzAnnotation_do_calculations(SEXP measured_massSEXP, SEXP maxSEXP, SEXP minSEXP, SEXP toleranceSEXP, SEXP chargeSEXP, SEXP applygrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type measured_mass(measured_massSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type max(maxSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type min(minSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< double >::type charge(chargeSEXP);
    Rcpp::traits::input_parameter< bool >::type applygr(applygrSEXP);
    __result = Rcpp::wrap(do_calculations(measured_mass, max, min, tolerance, charge, applygr));
    return __result;
END_RCPP
}
