# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
mfGen <- function(measured_mass, max, min, tolerance, charge, applygr) {
    .Call('mzAnnotation_mfGen', PACKAGE = 'mzAnnotation', measured_mass, max, min, tolerance, charge, applygr)
}

