# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_calculations <- function(measured_mass, max, min, tolerance, charge, applygr) {
    .Call('mzAnnotation_do_calculations', PACKAGE = 'mzAnnotation', measured_mass, max, min, tolerance, charge, applygr)
}

