# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master,devel]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          rtools-version: "42"
      
      - name: Install Windows system dependencies
        if: runner.os == 'Windows'
        run: |
          download.file(
            'https://github.com/girke-lab/ChemmineOB/releases/download/3.1.1/openbabel3r42.zip',
            'D:/a/openbabel3r42.zip')
          untar('D:/a/openbabel3r42.zip',
            exdir = 'D:/a')
        shell: Rscript {0}
      
      - name: Set system PATH
        if: runner.os == 'Windows'
        run: |
          echo "D:\a\openbabel3r42\bin\x64\bin" >> $GITHUB_PATH
          echo "D:\a\_temp\Library\zlibbioc\libs\x64" >> $GITHUB_PATH
          echo "D:\a\openbabel3r42\bin\i386\bin" >> $GITHUB_PATH
          echo "D:\a\_temp\Library\zlibbioc\libs\i386" >> $GITHUB_PATH
        shell: bash
        
      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt install libopenbabel-dev
          
      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install open-babel

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck
        env:
          OPEN_BABEL_SRC: D:/a/openbabel3r42/src
          OPEN_BABEL_BIN: D:/a/openbabel3r42/bin

      - uses: r-lib/actions/check-r-package@v1
